// <auto-generated />
using System;
using LambertFinanceApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LambertFinanceApp.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20230516161105_category")]
    partial class category
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("LambertFinanceApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fun"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Grocery"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Utilities"
                        });
                });

            modelBuilder.Entity("LambertFinanceApp.Models.Transactions", b =>
                {
                    b.Property<int>("transactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("amount")
                        .HasColumnType("REAL");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("income")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("returned")
                        .HasColumnType("INTEGER");

                    b.HasKey("transactionId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("LambertFinanceApp.Models.Transactions", b =>
                {
                    b.HasOne("LambertFinanceApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
